apiVersion: v1
kind: Namespace
metadata:
  name: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - args:
        env:
        - name: ENV
          value: prod
        image: resuzuke/technical-task:$TAG
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          httpGet:
            path: /health
            port: http
          timeoutSeconds: 5
        name: api
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          httpGet:
            path: /ready
            port: http
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 512Mi
        startupProbe:
          failureThreshold: 60
          periodSeconds: 10
          successThreshold: 1
          httpGet:
            path: /ready
            port: http
          timeoutSeconds: 5
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: backend
        matchLabelKeys:
        - pod-template-hash
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: backend
  type: ClusterIP
